### ISSUE TITLE
How can I determine how many sales of item X were made on a date?

### ISSUE THREAD

**Issue by otang** [square/connect-ruby-sdk#44]
Hi, I'm having trouble finding the APIs that allow me to answer this question: How many of item X did we sell on 2018-08-01.

Can you help point me in the right direction?

**Comment by StephenJosey** [comment]
Hi @otang!

In order to review itemizations, you will need to use `order_id`'s (by calling `CreateOrder`), and attaching it to a `Charge` request. After that, if you need to retrieve item sales from a particular date, you can call `ListTransactions` with `begin_time` and `end_time`, and the `Transaction` objects will include a `order_id` field, which you can then pass to the `BatchRetrieveOrders` endpoint to view the items sold in the order.

Also, if you are using Square POS to take payments instead of our APIs, then there will not be an `order_id`, and you will need to use V1's `ListPayments` instead which will show the POS itemizations.

Please let me know if you have any further questions about this!

References:
https://docs.connect.squareup.com/cookbook/orders-and-transactions
https://docs.connect.squareup.com/api/connect/v1#navsection-payments
